name: Push to MongoDB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_mongo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install pymongo

    - name: Push document to MongoDB
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        python - <<EOF
        from pymongo.mongo_client import MongoClient
        from pymongo.server_api import ServerApi
        from datetime import datetime

        uri = "${{ secrets.MONGO_URI }}"

        # Connect to MongoDB
        client = MongoClient(uri, server_api=ServerApi('1'))
        try:
            client.admin.command('ping')
            print("Pinged your deployment. Successfully connected to MongoDB!")
        except Exception as e:
            print(e)
            raise SystemExit(1)

        # Connect to the 'Debi' database
        db = client['Debi']
        git_collection = db['Git']
        document = {
            "timestamp": datetime.utcnow().isoformat(),
            "message": "New commit pushed or workflow manually triggered",
            "source": "GitHub Actions"
        }
        git_collection.insert_one(document)
        print("Document successfully inserted into the Git collection.")
        EOF
